name: Discord PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: peter-evans/discord-webhook-action@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "A new PR has been opened: ${{ github.event.pull_request.title }}. Check it out: ${{ github.event.pull_request.html_url }}"
